apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
      - name: jenkins-project
        image: norhanhatem0187/final-project:latest
        ports:
        - containerPort: 8080
